### ISSUE TITLE
passing parameter to the context element

### ISSUE THREAD

**Issue by nurulmac11** [wesbos/React-Context#1]
Can I pass paramaters to the context functions ? Like;
```
growAYearOlder: (intValue) => this.setState({
          age: this.state.age + intValue
        })
```

then 
`
<button onClick={context.growAYearOlder(5)}>🍰🍥🎂</button>`

**Comment by wesbos** [comment]
Yes, but it would need to be called onClick with an inline function:

```js
<button onClick={() => context.growAYearOlder(5)}>🍰🍥🎂</button>
```
